# Generated by Django 6.1.1 on 2026-09-08 09:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(db_index=True, decimal_places=2, help_text='Standard starting price in INR/local currency.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether service is available for booking.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon or CSS class identifier.', max_length=50)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('PROVIDER', 'Service Provider'), ('COOP_ADMIN', 'Cooperative Administrator'), ('PLATFORM_ADMIN', 'Platform Administrator')], db_index=True, default='CUSTOMER', help_text='Designates the role of the user within the platform.', max_length=20)),
                ('phone_number', models.CharField(blank=True, db_index=True, help_text='Contact phone number.', max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile image.', null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, help_text='Short bio or user description.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total agreed transaction cost for the service.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('service_address', models.TextField(help_text='Location where service is to be rendered.')),
                ('special_instructions', models.TextField(blank=True, help_text='Customer instructions or notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.PROTECT, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.service')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(help_text='Category under which this service falls.', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.servicecategory'),
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coop_member_id', models.CharField(blank=True, help_text='Cooperative membership identifier code.', max_length=50, null=True, unique=True)),
                ('skills', models.JSONField(default=list, help_text="List of skill tags or categories (e.g. ['Plumbing', 'Electrical']).")),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('OFFLINE', 'Offline')], db_index=True, default='OFFLINE', max_length=20)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Base hourly rate for services rendered.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('rating', models.DecimalField(db_index=True, decimal_places=2, default=0.0, help_text='Average rating out of 5.00.', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_reviews_count', models.PositiveIntegerField(default=0)),
                ('service_radius_km', models.PositiveIntegerField(default=10, help_text='Maximum service coverage distance in kilometers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'PROVIDER'}, on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worker Profile',
                'verbose_name_plural': 'Worker Profiles',
                'ordering': ['-rating', '-total_reviews_count'],
            },
        ),
        migrations.CreateModel(
            name='CoopEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total revenue collected from booking.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('commission_fee', models.DecimalField(decimal_places=2, help_text='Platform operation & maintenance commission fee.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('coop_dividend_pool', models.DecimalField(decimal_places=2, help_text='Amount funneled to cooperative member dividend pool for profit distribution.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('worker_payout', models.DecimalField(decimal_places=2, help_text='Net direct payout to service provider.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('payout_status', models.CharField(choices=[('PENDING', 'Pending Distribution'), ('PROCESSING', 'Processing'), ('PAID', 'Paid Out'), ('RETAINED', 'Retained in Dividend Pool')], db_index=True, default='PENDING', max_length=20)),
                ('payout_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='earning_record', to='core.booking')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coop_earnings', to='core.workerprofile')),
            ],
            options={
                'verbose_name': 'Coop Earning Record',
                'verbose_name_plural': 'Coop Earning Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worker_bookings', to='core.workerprofile'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'is_active'], name='core_custom_role_1cf58e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='core_custom_email_a5d01e_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active'], name='core_servic_categor_ec0a06_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['base_price'], name='core_servic_base_pr_e25af0_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['availability_status', 'verification_status'], name='core_worker_availab_03e3f2_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['rating'], name='core_worker_rating_ddd27c_idx'),
        ),
        migrations.AddIndex(
            model_name='coopearning',
            index=models.Index(fields=['worker', 'payout_status'], name='core_coopea_worker__ef69c8_idx'),
        ),
        migrations.AddIndex(
            model_name='coopearning',
            index=models.Index(fields=['payout_status'], name='core_coopea_payout__671e16_idx'),
        ),
        migrations.AddIndex(
            model_name='coopearning',
            index=models.Index(fields=['created_at'], name='core_coopea_created_9acf66_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'status'], name='core_bookin_custome_71d916_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['worker', 'status'], name='core_bookin_worker__bd8e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['scheduled_time'], name='core_bookin_schedul_f0922c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='core_bookin_status_fe12a1_idx'),
        ),
    ]
