# Generated by Django 6.1.1 on 2026-09-08 11:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional note from worker.')),
                ('expressed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Interest',
                'verbose_name_plural': 'Job Interests',
                'ordering': ['expressed_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('budget_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('service_address', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('transaction_ref', models.UUIDField(default=uuid.uuid4, help_text='Simulated unique transaction reference.', unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 (worst) to 5 (best).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional written feedback.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='job_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when a worker accepted the job.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], db_index=True, default='UNPAID', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, help_text='City of residence.', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude for proximity-based matching.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude for proximity-based matching.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pincode',
            field=models.CharField(blank=True, help_text='PIN / ZIP code.', max_length=10),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='latitude',
            field=models.FloatField(blank=True, help_text="Worker's home/base GPS latitude.", null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='longitude',
            field=models.FloatField(blank=True, help_text="Worker's home/base GPS longitude.", null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coopearning',
            name='commission_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='coopearning',
            name='coop_dividend_pool',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='coopearning',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='coopearning',
            name='worker_payout',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Standard starting price in INR.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='skills',
            field=models.JSONField(default=list, help_text='List of ServiceCategory slugs this worker is skilled in.'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status'], name='core_bookin_payment_324a5e_idx'),
        ),
        migrations.AddField(
            model_name='jobinterest',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_interests', to='core.workerprofile'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_postings', to='core.workerprofile'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='core.servicecategory'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobinterest',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='core.jobposting'),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='core.booking'),
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(help_text='Each completed booking can have exactly one review.', on_delete=django.db.models.deletion.PROTECT, related_name='review', to='core.booking'),
        ),
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.PROTECT, related_name='given_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_reviews', to='core.workerprofile'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['status'], name='core_jobpos_status_f61fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['category', 'status'], name='core_jobpos_categor_aa8e39_idx'),
        ),
        migrations.AddIndex(
            model_name='jobinterest',
            index=models.Index(fields=['posting', 'status'], name='core_jobint_posting_13f339_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobinterest',
            unique_together={('posting', 'worker')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['worker'], name='core_review_worker__4653d6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['customer'], name='core_review_custome_86ec1f_idx'),
        ),
    ]
